services:
  - type: web
    name: claims-management-system
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn claims_interface.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
    healthCheckPath: /dashboard/
    autoDeploy: true

databases:
  - name: claims-db
    databaseName: claims_db
    user: claims_user
    plan: free
