services:
  - type: web
    name: claims-management-system
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: claims_interface.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
    healthCheckPath: /health/
    autoDeploy: true
