# Generated by Django 4.2.7 on 2025-08-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('claim_id', models.IntegerField()),
                ('denial_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('cpt_codes', models.CharField(blank=True, max_length=500, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Claim Detail',
                'verbose_name_plural': 'Claim Details',
                'db_table': 'claim_detail',
            },
        ),
        migrations.CreateModel(
            name='ClaimList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('billed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('insurer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Claim List',
                'verbose_name_plural': 'Claim Lists',
                'db_table': 'claim_list',
            },
        ),
    ]
