# Generated by Django 4.2.7 on 2025-08-06 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_alter_claimdetail_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimdetail',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='claimdetail',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='claimlist',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='claimlist',
            name='updated_date',
        ),
    ]
