# Generated by Django 4.2.7 on 2025-08-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_claimnote_claimflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimdetail',
            name='claim_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='claimlist',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
