# Generated by Django 4.2.7 on 2025-08-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_alter_claimdetail_claim_id_alter_claimlist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimflag',
            name='flagged_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='claimnote',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
